<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>..\favicon.ico</ApplicationIcon>
    <AssemblyName>Dock</AssemblyName>
    <RootNamespace>Dock</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\favicon.ico" Link="favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
